---
title: "US Inflation Forecast"
author: "Dr. Paulo Gustavo Grahl, CFA"
date: "2022-03-10"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE,
    include = TRUE
)
require(fpp3)
require(tidyverse)
require(tsbox)
require(ATAforecasting)
```

## Introduction

```{r}
# load data --------------------------------------------------------------------
cpiboard <- pins::board_folder("E:/RData")
cpidb <- pins::pin_read(cpiboard, "USCPI")
cpi.series <- pins::pin_read(cpiboard, "USCPI-SERIES")
cpi.item   <- pins::pin_read(cpiboard, "USCPI-ITEM")

# owners' equivalent rent 
oer <- filter(cpidb, series_id == "CUSR0000SEHC")
autoplot(oer, value)

train_data <- aus_retail %>% filter(State == "New South Wales",
                      Industry == "Department stores",
                      `Series ID` == "A3349790V") %>% 
  tsbox::ts_ts()

bc_attr_set <- ATA.BoxCoxAttr(bcMethod = "loglik", bcLower = 0, bcUpper = 1)
fit_bc <- ATA(train_data, seasonal.type = "M", model.type = "A", seasonal.test = TRUE, seasonal.model = "decomp", plot.out = TRUE, transform.method = "Box_Cox", transform.order = "before", transform.attr = bc_attr_set, negative.forecast = FALSE)
```

